### ISSUE TITLE
handle missing metadata

### ISSUE THREAD

**Issue by ungarj** [ungarj/s2reader#7]
When running ``s2_transform`` on ``S2A_MSIL1C_20170809T100031_N0205_R122_T32TQT_20170809T100028.SAFE`` (can be downloaded on [DHUS](https://scihub.copernicus.eu/dhus/)), a ``KeyError`` is raised:

```
Traceback (most recent call last):
  File "/home/ungarj/.virtualenvs/s2reader/bin/s2_transform", line 11, in <module>
    load_entry_point('s2reader', 'console_scripts', 's2_transform')()
  File "/home/ungarj/github/s2reader/s2reader/cli/transform.py", line 409, in main
    xml_string = EOOM_TEMPLATE_PRODUCT.format(**params)
KeyError: 'archivingCenter'
```
I propose, we should add custom exceptions if some expected metadata tags are missing. I'm not sure though whether ``s2_transform`` can live without the archivingCenter tag.

@constantinius, what do you think?

**Comment by ungarj** [comment]
also, ``PVI_FILENAME`` is not available in test datasets (presumably because it was introduced later on), so calling the ``pvi_path`` raises an opaque exception
